const dropdownOptions = [
    { value: 'Accounting Manager', label: 'Accounting Manager' },
    { value: 'Advertising Manager', label: 'Advertising Manager' },
    { value: 'Android Developer', label: 'Android Developer' },
    { value: 'Anti-Money Laundering (AML) Officer', label: 'Anti-Money Laundering (AML) Officer' },
    { value: 'API Engineer (BE)', label: 'API Engineer (BE)' },
    { value: 'Angular Developer (FE)', label: 'Angular Developer (FE)' },
    { value: 'Asset Manager', label: 'Asset Manager' },
    { value: 'Brand Manager', label: 'Brand Manager' },
    { value: 'Branch Manager', label: 'Branch Manager' },
    { value: 'Business Analyst', label: 'Business Analyst' },
    { value: 'Campaign Manager', label: 'Campaign Manager' },
    { value: 'Chief Compliance Officer (CCO', label: 'Chief Compliance Officer (CCO' },
    { value: 'Chief Data Officer (CDO)', label: 'Chief Data Officer (CDO)' },
    { value: 'Chief Executive Officer (CEO)', label: 'Chief Executive Officer (CEO)' },
    { value: 'Chief Financial Officer (CFO)', label: 'Chief Financial Officer (CFO)' },
    { value: 'Chief Information Security Officer (CISO)', label: 'Chief Information Security Officer (CISO)' },
    { value: 'Chief Investment Officer (CIO)', label: 'Chief Investment Officer (CIO)' },
    { value: 'Chief Marketing Officer (CMO)', label: 'Chief Marketing Officer (CMO)' },
    { value: 'Chief Operations Officer (COO)', label: 'Chief Operations Officer (COO)' },
    { value: 'Chief Risk Officer (CRO)', label: 'Chief Risk Officer (CRO)' },
    { value: 'Cloud Engineer (BE)', label: 'Cloud Engineer (BE)' },
    { value: 'Compliance Analyst', label: 'Compliance Analyst' },
    { value: 'Compliance Manager', label: 'Compliance Manager' },
    { value: 'Content Writer', label: 'Content Writer' },
    { value: 'Corporate Banking Manager', label: 'Corporate Banking Manager' },
    { value: 'Credit Analyst', label: 'Credit Analyst' },
    { value: 'Customer Relationship Officer', label: 'Customer Relationship Officer' },
    { value: 'Customer Service Manager', label: 'Customer Service Manager' },
    { value: 'Data Analyst', label: 'Data Analyst' },
    { value: 'Data Scientist', label: 'Data Scientist' },
    { value: 'Database Administrator (BE)', label: 'Database Administrator (BE)' },
    { value: 'DevOps Engineer (BE)', label: 'DevOps Engineer (BE)' },
    { value: 'Digital Banking Manager', label: 'Digital Banking Manager' },
    { value: 'Digital Marketing Specialist', label: 'Digital Marketing Specialist' },
    { value: 'Event Coordinator', label: 'Event Coordinator' },
    { value: 'Financial Controller', label: 'Financial Controller' },
    { value: 'Financial Planner', label: 'Financial Planner' },
    { value: 'Flutter Developer', label: 'Flutter Developer' },
    { value: 'Frontend Architect (FE)', label: 'Frontend Architect (FE)' },
    { value: 'Frontend Developer (FE)', label: 'Frontend Developer (FE)' },
    { value: 'Frontend Software Engineer (FE)', label: 'Frontend Software Engineer (FE)' },
    { value: 'Frontend Team Lead (FE)', label: 'Frontend Team Lead (FE)' },
    { value: 'Fraud Investigator', label: 'Fraud Investigator' },
    { value: 'Graphic Designer', label: 'Graphic Designer' },
    { value: 'Human Resources Manager', label: 'Human Resources Manager' },
    { value: 'Information Security Analyst', label: 'Information Security Analyst' },
    { value: 'Insurance Specialist', label: 'Insurance Specialist' },
    { value: 'Internal Auditor', label: 'Internal Auditor' },
    { value: 'Investment Advisor', label: 'Investment Advisor' },
    { value: 'iOS Developer', label: 'iOS Developer' },
    { value: 'IT Manager', label: 'IT Manager' },
    { value: 'JavaScript Developer (FE)', label: 'JavaScript Developer (FE)' },
    { value: 'Legal Counsel', label: 'Legal Counsel' },
    { value: 'Loan Officer', label: 'Loan Officer' },
    { value: 'Market Research Analyst', label: 'Market Research Analyst' },
    { value: 'Marketing Analyst', label: 'Marketing Analyst' },
    { value: 'Marketing Manager', label: 'Marketing Manager' },
    { value: 'Mobile App Developer', label: 'Mobile App Developer' },
    { value: 'Mobile Architect', label: 'Mobile Architect' },
    { value: 'Mobile Software Engineer', label: 'Mobile Software Engineer' },
    { value: 'Mobile Team Lead', label: 'Mobile Team Lead' },
    { value: 'Mobile UI/UX Engineer', label: 'Mobile UI/UX Engineer' },
    { value: 'Mortgage Specialist', label: 'Mortgage Specialist' },
    { value: 'Operations Manager', label: 'Operations Manager' },
    { value: 'Portfolio Manager', label: 'Portfolio Manager' },
    { value: 'PR Manager', label: 'PR Manager' },
    { value: 'Private Banking Manager', label: 'Private Banking Manager' },
    { value: 'Product Manager', label: 'Product Manager' },
    { value: 'Project Manager', label: 'Project Manager' },
    { value: 'React Developer (FE)', label: 'React Developer (FE)' },
    { value: 'React Native Developer', label: 'React Native Developer' },
    { value: 'Relationship Manager', label: 'Relationship Manager' },
    { value: 'Retail Banking Manager', label: 'Retail Banking Manager' },
    { value: 'Risk Analyst', label: 'Risk Analyst' },
    { value: 'Risk Manager', label: 'Risk Manager' },
    { value: 'Securities Trader', label: 'Securities Trader' },
    { value: 'Senior Executive Vice President', label: 'Senior Executive Vice President' },
    { value: 'Social Media Manager', label: 'Social Media Manager' },
    { value: 'Software Developer', label: 'Software Developer' },
    { value: 'Systems Engineer (BE)', label: 'Systems Engineer (BE)' },
    { value: 'Tax Specialist', label: 'Tax Specialist' },
    { value: 'Technical Support Specialist', label: 'Technical Support Specialist' },
    { value: 'Training and Development Manager', label: 'Training and Development Manager' },
    { value: 'Treasury Manager', label: 'Treasury Manager' },
    { value: 'UI/UX Engineer (FE)', label: 'UI/UX Engineer (FE)' },
    { value: 'Vice President', label: 'Vice President' },
    { value: 'Vue.js Developer (FE)', label: 'Vue.js Developer (FE)' },
    { value: 'Wealth Management Advisor', label: 'Wealth Management Advisor' },
    { value: 'Web Designer', label: 'Web Designer' },

];

export default dropdownOptions;

